[systemslogs]
type = "LogstreamerInput"
log_directory = "/var/log/syslog/systems"
file_match = '(?P<System>[^/]+)/(?P<Year>\d+)-(?P<Month>\d+)-(?P<Day>\d+).log'
priority = ["Year","Month","Day"]
oldest_duration = "2h"
decoder = "systemslogs_transform_decoder"

[systemslogs_transform_decoder]
type = "PayloadRegexDecoder"
match_regex = '^(?P<syslogtimestamp>[A-Z][a-z]+\s+\d+\s\d+:\d+:\d+)\s(?P<hostname>.+?)\s(?P<program>.+?)(\[(?P<pid>.+?)\])?:\s(?P<summary>.*)'

[systemslogs_transform_decoder.message_fields]
Type = "syslog"
Logger = "heka"
summary = "%summary%"
Severity = "INFO"
Hostname= "%hostname%"
Timestamp="%syslogtimestamp%"
details.timestamp = "%syslogtimestamp%"
details.hostname = "%hostname%"
details.program = "%program%"
details.processid = "%pid%"

# Start commenting here if you don't want any stdout
[stdout]
type = "LogOutput"
message_matcher = "TRUE"
#payload_only = true
# Finish commenting here

[ElasticSearchOutput]
message_matcher = "Type!='heka.all-report'"
cluster = "mozdefqa"
index = "events"
type_name = "event"
server = "http://mozdef.example.com:8080"
format = "clean"
flush_interval = 1000
flush_count = 10
